config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :game_instances, path: "game", only: [:create, :show, :update] do
    collection do
      get :random
    end
  end
end

app/models/game_attribute.rb
class GameAttribute < ActiveRecord::Base
  belongs_to :game_instance
end

app/models/game_instance.rb
class GameInstance < ActiveRecord::Base
  extend FriendlyId
  include TwitterHelper
  friendly_id :name, use: :slugged

  def shut_down
    send_tweet("The #{self.name} game was shut down!")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_instances_controller.rb
class GameInstancesController < ApplicationController
  include GameUrlHelper
  before_action :find_game_instance, only: [:show, :update]

  def create
    @game_instance = GameInstance.create(name: unique_game_name)
    redirect_to @game_instance
  end

  def show
  end

  def update
    @game_instance.update_attributes(game_params)
    if @game_instance.status == "won"
      redirect_to game_instance_path(@game_instance.slug)
    end
  end

  def random
    if GameInstance.any?
      redirect_to GameInstance.all.sample
    else
      redirect_to root_path
    end
  end

  private

  def game_params
    params.require(:game_instance).permit(:jump_power, :down_method, :status, :objectives)
  end
  def find_game_instance
    @game_instance = GameInstance.friendly.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @new_game = GameInstance.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_url_helper.rb
module GameUrlHelper

  def unique_game_name
    name_taken = true
    while name_taken
      name = game_url_fruit_options.sample + " " + game_url_body_part_options.sample
      name_taken = GameInstance.where(name: name).any?
    end
    return name
  end

  def game_url_fruit_options
    ["Apricot", "Artichoke", "Asparagus", "Avocado", "Banana", "Broccoli", "Cabbage", "Carrot", "Celery", "Cucumber", "Fig", "Garlic", "Grapefruit", "Kiwi", "Leek", "Lemon", "Lettuce", "Lime", "Mango", "Melon", "Olive", "Onion", "Papaya", "Peach", "Pear", "Pineapple", "Plum", "Potato", "Prune", "Pumpkin", "Radish", "Raisin", "Rhubarb", "Shallot", "Spinach", "Squash", "Tangerine", "Tomato", "Turnip", "Zucchini"]
  end

  def game_url_body_part_options
    ["Ankles", "Arms", "Brains", "Claws", "Ears", "Elbows", "Eyes", "Feathers", "Feet", "Fingers", "Fins", "Hands", "Hearts", "Hips", "Kidneys", "Knees", "Legs", "Lips", "Lungs", "Necks", "Nose", "Nostrils", "Paws", "Shins", "Shoulders", "Spines", "Spleens", "Tails", "Teeth", "Thighs", "Toes", "Tongues", "Torsos", "Whiskers", "Wings", "Wrists"]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
  def send_tweet(tweet)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
      config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
      config.access_token        = ENV["TWITTER_ACCESS_TOKEN"]
      config.access_token_secret = ENV["TWITTER_ACCESS_SECRET"]
    end
    client.update(tweet)
  end
end

app/views/game_instances/show.html.haml
/ %h1= @game_instance.name
/ %h3
/   %span Your score is
/   %span#game-score= @game_instance.test_value

/ = form_for @game_instance, method: :put, remote: true do |f|
/   = f.submit "Increment"

#gamerails
- if @game_instance.status == "won"
  = image_tag("trophy.jpg")
- else
  #orientation
  :javascript
    (function () {
        var game = new Phaser.Game(512, 384, Phaser.CANVAS, 'game');

        game.state.add('Boot', Appleheels.Boot);
        game.state.add('Preloader', Appleheels.Preloader);
        game.state.add('MainMenu', Appleheels.MainMenu);
        game.state.add('Game', Appleheels.Game);
        game.state.add('TerminalMenuOne', Appleheels.TerminalMenuOne);
        game.state.add('TerminalMenuTwo', Appleheels.TerminalMenuTwo);
        game.state.add('TerminalMenuThree', Appleheels.TerminalMenuThree);

        game.state.start('Boot');

        game.gameId = "#{@game_instance.id}";
        game.victoryStatus = "#{@game_instance.status}";
        game.jumpPower = "#{@game_instance.jump_power}";
        game.downVerb = "#{@game_instance.down_method}";
        game.objectives = "#{@game_instance.objectives}";

      })();

app/views/home/index.html.haml
.home-screen-container
  .title Appleheels
  = form_for @new_game do |f|
    = f.submit "Create Game"
  = link_to "Random Game", random_game_instances_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appleheels</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8" />
  <script src="//cdn.jsdelivr.net/phaser/2.2.2/phaser.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>